# Generated by Django 2.1.1 on 2018-09-23 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(max_length=18)),
                ('house_number', models.CharField(default='', max_length=3)),
                ('street', models.CharField(default='', max_length=50)),
                ('area', models.CharField(default='', max_length=30)),
                ('city', models.CharField(default='', max_length=30)),
                ('county', models.CharField(default='', max_length=30)),
                ('post_code', models.CharField(default='', max_length=10)),
                ('country', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('profile_description', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_pic')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Contact')),
            ],
        ),
    ]
