# Generated by Django 2.1.1 on 2018-09-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(default='', upload_to='cars'),
        ),
    ]
